version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: "marswar-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d:ro
      - ./staticfiles/:/static
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
      - certbot
  web:
    build: .
    container_name: "marswar"
    command: ./start.sh
    volumes:
      - .:/app
      - ./staticfiles/:/app/staticfiles/
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: "marswar-db"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw