# Generated by Django 3.2.14 on 2022-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmarswar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
