# Generated by Django 3.2.14 on 2022-10-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmarswar', '0002_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='event_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
