# Generated by Django 3.2.14 on 2022-10-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmarswar', '0003_bracket_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player2_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
