# Generated by Django 3.2.14 on 2022-10-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmarswar', '0005_auto_20221015_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rating_change',
            field=models.IntegerField(default=0),
        ),
    ]
