# Generated by Django 3.2.14 on 2022-11-20 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailwindButton',
            fields=[
                ('label', models.CharField(blank=True, help_text='The text displayed inside the button', max_length=255, verbose_name='Label')),
                ('link', models.CharField(blank=True, help_text='The URL that the button points to', max_length=1000, verbose_name='Link')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='theme_tailwindbutton', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
